#!/usr/bin/env bash

kube_list_all() {
    kubectl get services
    kubectl get pods --all-namespaces -o wide
}

kube_list_pods() {
    kubectl get pods -o go-template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}'
}

kube_events() {
    kubectl get events --sort-by='{.lastTimestamp}'
}

kube_export_all() {
    kubectl get all --export -o yaml
}

kube_exe() {
    kubectl exec -it $1 -- ${@:2}
}
