#!/usr/bin/env bash

kube_list_all() {
    kubectl get services
    kubectl get pods --all-namespaces -o wide
}

kube_list_pods() {
    kubectl get pods -o go-template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}'
}

kube_pod_details() {
    kubectl describe pod $1
}
