#!/usr/bin/env bash

kube_list_pods() {
    kubectl get pods -o go-template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}'
}

kube_events() {
    kubectl get events --sort-by='{.lastTimestamp}'
}

kube_export_all() {
    kubectl get all --export -o yaml
}

kube_debug() {
  kubectl run -it --rm debug --image=${1-debian} --restart=Never -- bash
}
