#!/usr/bin/env bash

show_networks() {
    virsh -c qemu:///system net-list --all
}

show_storage_pools() {
    virsh -c qemu:///system pool-list --all
}

show_storage_pools_xml() {
    virsh -c qemu:///system pool-dumpxml $1
}

# $1 network name
show_network_xml() {
    virsh -c qemu:///system net-dumpxml $1
}

start_network() {
    virsh -c qemu:///system net-start $1
}
