#!/usr/bin/env zsh
# mind this uses `type` function available only on ZSH

SEC_UTIL_LOC="$(dirname $(readlink -f $0))"
source $SEC_UTIL_LOC/cert_functions

# Generate keypair signed by given CA
# asks for countryName, stateOrProvince, etc.
generate_server_keypair_signed_interactive() {(set -e  # fail early in function
  name="$1"
  out="$2"
  ca_key="$3"
  ca_crt="$4"
  export UTIL_CA_PRIV_KEY="$ca_key"
  export UTIL_CA_CERT="$ca_crt"
  export UTIL_SERVER_FQDN=${5-$name}
  mkdir -p "$out/private"
  mkdir -p "$out/certs"
  mkdir -p "$out/newcerts"  # possibly remove
  touch "$out/index.txt"
  echo '01' > "$out/serial"
  server_config="$SEC_UTIL_LOC/openssl-server.cnf"
  ca_config="$SEC_UTIL_LOC/openssl-ca.cnf"
  server_key="$out/private/$name.key"
  server_cert="$out/certs/$name.crt"
  server_csr="$out/$name.csr"

  echo "Generating private key: $server_key"
  gen_ec_key $server_key
  echo "Key: $server_key generated"

  echo "Generating CSR: $server_csr"
  gen_csr_interactive "$server_key" "$server_csr" "$server_config" "$out"
  echo "CSR: $server_csr generated"

  echo "Signing CSR: $server_cert"
  gen_csr_sign "$server_csr" "$server_cert" "$ca_config" "$out"
  echo "Cert: $server_cert generated"
)}
