#!/usr/bin/env bash

# dump dhcp traffic
# [$1] interface (any otherwise)
# [$2] output file (/tmp/dhcp.pcap otherwise)
sniff_dhcp() {
    local ifc=${1-any}
    local location=${2:-/tmp/dhcp.pcap}
    tcpdump -i $ifc -w $location port 67 or port 68 -e -n
}

# display remotely run tcpdump in local wireshark
# remote user must have permissions to run tcpdump
# https://peternixon.net/news/2012/01/28/configure-tcpdump-work-non-root-user-opensuse-using-file-system-capabilities/
grab_remote_tcpdump() {
    ssh -C $1 "tcpdump -i $2 -s0 -U -w - $3" | wireshark -k -i -
}
_grab_remote_tcpdump() {
    _arguments \
        '1:user@ip' \
        '2:interface (at remote)' \
        '3:optional filter'
}
compdef _grab_remote_tcpdump grab_remote_tcpdump
