#!/usr/bin/env bash

# dump dhcp traffic
# [$1] interface (any otherwise)
# [$2] output file (/tmp/dhcp.pcap otherwise)
sniff_dhcp() {
    local ifc=${1-any}
    local location=${2:-/tmp/dhcp.pcap}
    tcpdump -i $ifc -w $location port 67 or port 68 -e -n
}
