#!/usr/bin/env bash

# show information about total space available (pool of raw storage)
show_btrfs_fs() {
    btrfs filesystem show
}

# show detailed information about allocated space (from pool)
# $1 mountpoint of btrfs fs
show_btrfs_fs_detailed() {
    btrfs filesystem df $1
}

# $1 mount point
show_subvolumes() {
    btrfs subvolume list $1
}

# $1 mount points
show_errors() {
    btrfs dev stats $1
}

# $1 directory containing btrfs subvolume
create_subvol() {
    if [ -z $1 ]; then
        echo "Usage: $0: <path for subvolume>"
        return 1
    fi
    btrfs subvolume create $1
}
