#!/usr/bin/env bash

# provide list of wallpapers to set for consecutive desktops
set_wallpaper() {
  local allargs="$@"
  # build string to be pasted in JS snipped below...
  local wallpapers="['"
  for w in $@; do
    wallpapers="$wallpapers$w', '"
  done
  wallpapers="${wallpapers::-3}]"

  local script="
var allDesktops = desktops();
var wallpapers = $wallpapers;
for (i=0;i<allDesktops.length;i++) {
  d = allDesktops[i];
  d.wallpaperPlugin = 'org.kde.image';
  d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General');
  d.writeConfig('Image', wallpapers[i%wallpapers.length]);
}
"
  qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$script"
}
