#!/usr/bin/env bash

# provide list of wallpapers to set for consecutive desktops
# broken on newer Plasma
set_wallpaper() {
  local script="var allDesktops = desktops();"
  local i=0
  for img in "$@"; do
    script=$script"
if (allDesktops.length > $i) {
d = allDesktops[$i];
d.wallpaperPlugin = 'org.kde.image';
d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General');
d.writeConfig('Image', \"$img\");
}
"
    ((i++))
  done
  qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$script"
}
