#!/usr/bin/env bash

kube_list_pods() {
  kubectl get pods -o go-template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}'
}

kube_events() {
  kubectl get events --sort-by='{.lastTimestamp}'
}

kube_debug_once() {
  kubectl run -it --rm debug --image=${1-debian} --restart=Never -- bash
}

kube_debug() {
  cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: debug
  name: ${1-debug}
  namespace: ${2-default}
spec:
  securityContext:
    runAsUser: 0
  containers:
    - image: debian:bullseye
      name: debug
      command:
        - bash
      stdin: true
      tty: true
      securityContext:
        privileged: true
EOF
  kubectl wait --for condition=ready --timeout=${3-10}s pod/${1-debug} -n ${2-default}
  kubectl exec -it ${1-debug} -n ${2-default} -- bash
}
