#!/usr/bin/env bash

git_untracked() {
  git ls-files . --exclude-standard --others
}

mrepo_branch_del() {
  local base_dir="$1"
  local branch_to_remove="$2"
  if [ -z "${branch_to_remove}" ]; then
    echo "Usage: $0 <base_dir> <branch_to_remove>"
    return 4
  fi
  echo "Branch: $branch_to_remove removal in all repositories under: $base_dir"
  for dir in "$base_dir"/*/; do
    if [ -d "$dir/.git" ]; then
      echo "Removing branch $branch_to_remove in $dir"
      (cd "$dir" && git branch -d "$branch_to_remove")
    fi
  done
}

mrepo_branch_create() {
  local repo="$1"
  local branch_name="$2"

  if [ -z "$branch_name" ] || [ -z "$repo" ]; then
      echo "Error: Branch name is required."
      echo "Usage: $0 <repo> <branch_name>"
      return 12
  fi

  pushd "$repo" || return 13

  git checkout -b "$branch_name"

  # todo onfailure popd

  popd
}
