#!/usr/bin/env bash

total_rss_vsz() {
    echo "Returning total RSS and VSZ of process(es): $1 (processes count: $(ps aux | grep "$1" | wc -l))"
    echo "RSS: $(ps aux | awk -v PROCESS="$1" '$11 ~ PROCESS {sum += $6} END {print sum}')"
    echo "VSZ: $(ps aux | awk -v PROCESS="$1" '$11 ~ PROCESS {sum += $5} END {print sum}')"
}
