#!/usr/bin/env bash

##############
# Alternatives
##############

show_all_manually_configured_alternatives() {
    for i in $(ls /etc/alternatives); do
        LANG=C update-alternatives --display $i 2>/dev/null;
    done | awk '/manual.mode/{print $1}'
}

# Manually update java alternatives
# Don't use this method. Use dedicated ppa oracle repo instead.
# $1 jinfo file name
# $2 priority
update_java_alternatives() {
    cat /usr/lib/jvm/".$1.jinfo" | grep -E '^(jre|jdk|hl)' | awk -v prio=$2 '{print "/usr/bin/" $2 " " $2 " " $3 " " prio " \n"}' | xargs -t -n4 sudo update-alternatives --verbose --install
    update-java-alternatives -s $1
}

######
# Misc
######

show_init_system() {
    cat /proc/1/comm
}

# force group of created files in given directory
# $1 directory
# $2 desired group
force_group_in_dir() {
    chgrp -R $2 $1
    chmod -R g+s $1
}

# convert string to its ASCII codes in hexadecimal, removing all spaces from the output hexstring
# $1 string
string_to_hex_trimmed() {
    echo -n "$1" | od -A n -t x1 | sed -e 's/^ *//' -e 's/ //g'
}

# convert string to its ASCII codes in hexadecimal
# $1 string
string_to_hex() {
    echo -n "$1" | od -A n -t x1 | sed 's/^ *//'
}

# hexdump file into one line
# $1 file path
dump_hex_one_line() {
    hexdump -e '16/1 "%02x"' $1
    #hexdump -e '16/1 "%02x " "\n"' $1
}
