#!/usr/bin/env bash

##############
# Alternatives
##############

show_all_manually_configured_alternatives() {
    for i in $(ls /etc/alternatives); do
        LANG=C update-alternatives --display $i 2>/dev/null;
    done | awk '/manual.mode/{print $1}'
}

# Manually update java alternatives
# Don't use this method. Use dedicated ppa oracle repo instead.
# $1 jinfo file name
# $2 priority
update_java_alternatives() {
    cat /usr/lib/jvm/".$1.jinfo" | grep -E '^(jre|jdk|hl)' | awk -v prio=$2 '{print "/usr/bin/" $2 " " $2 " " $3 " " prio " \n"}' | xargs -t -n4 sudo update-alternatives --verbose --install
    update-java-alternatives -s $1
}

######
# Systemd
######

# By default systemd log messages are not retained between boots
# Default journald setting is Storage=auto which means that persistent
# log store won't be created but will be used if exists
ensure_persistent_journal() {
    local log_location=/var/log/journal
    local systemd_conf_location=/etc/systemd/journald.conf

    if [ -d $log_location ] && grep -q "Storage=auto" $systemd_conf_location; then
        #doesn't matter if Storage=auto is commented out because this is the default either way
        echo "journald is already persistent"
        return 0;
    fi

    if grep -q "Storage=auto" $systemd_conf_location; then
        mkdir -p /var/log/journal
        systemd-tmpfiles --create --prefix $log_location
        echo "enabled persistent journald"
        return 0;
    fi
}

######
# Misc
######

show_init_system() {
    cat /proc/1/comm
}

# force group of created files in given directory
# $1 directory
# $2 desired group
force_group_in_dir() {
    chgrp -R $2 $1
    chmod -R g+s $1
}

# hexdump file into one line
# $1 file path
dump_hex_one_line() {
    hexdump -e '16/1 "%02x"' $1
    #hexdump -e '16/1 "%02x " "\n"' $1
}


swap_file() {
  mv $2 $2.tmp
  mv $1 $2
  mv $2.tmp $1
}