#!/usr/bin/env bash

# start parallel ssh session
# must be run within tmux session
# $1 username
# $2 list of hosts (IPs|hostnames)
tmux_parallel_ssh() {
    if [ -z "$2" ]; then
       echo -n "Please provide list of hosts separated by spaces"
    else
        local username=$1
        shift
        local hosts=( $* )
        tmux new-window "ssh ${hosts[0]}"
        #todo check if this escaping is needed for zsh only?
        unset hosts\[0\];
        for i in "${hosts[@]}"; do
            tmux split-window -h  "ssh $username@$i"
            tmux select-layout tiled > /dev/null
        done
        tmux select-pane -t 0
        tmux set-window-option synchronize-panes on > /dev/null
    fi
}
#todo make it not require tmux to already be running