#!/usr/bin/env bash

capture_stdout() {
  strace -p $1 -f -s9999 -e trace=write -e write=1,2 -o $2
}

# show IO call stats
show_io_stats() {
  strace -fce trace=open,read,write -p $1
}

# to strace process with its children use strace -f
