#!/usr/bin/env bash

_capture_stdout() {
  _arguments \
    "1:PID" \
    "2:log to file"
}
compdef _capture_stdout capture_stdout

_show_io_stats() {
  _arguments \
    "1:pid"
}
compdef _show_io_stats show_io_stats
